---

# http://docs.ansible.com/ansible/latest/set_fact_module.html
- name: Merge osquery_defaults and osquery variables
  set_fact:
    osquery_combined: "{{ osquery_defaults | combine(osquery, recursive=True) }}"

# https://docs.ansible.com/ansible/latest/modules/command_module.html
- name: Get the platform (i386 or amd64) of the virtual machine
  command: dpkg --print-architecture
  register: print_architecture

# https://docs.ansible.com/ansible/latest/modules/set_fact_module.html
- name: Set the actual platform value as a variable
  set_fact:
    platform: "{{ print_architecture.stdout }}"

# http://docs.ansible.com/ansible/latest/apt_key_module.html
- name: Add repository key
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B"
    state: present

# http://docs.ansible.com/ansible/latest/apt_repository_module.html
- name: Add Server repository
  apt_repository:
    repo: 'deb [arch=amd64] https://pkg.osquery.io/deb deb main'
    state: present

- name: Update apt cache
  apt: update_cache=yes

# http://docs.ansible.com/ansible/latest/apt_module.html
- name: Ensure specific version of packages is installed.
  apt:
    name: "osquery={{ osquery_combined.version}}"
    state: present
  when: "osquery_combined.version != 'latest'"

# http://docs.ansible.com/ansible/latest/apt_module.html
- name: Ensure latest version of packages is installed.
  apt:
    name: "osquery"
    state: present
  when: "osquery_combined.version == 'latest'"

# http://docs.ansible.com/ansible/latest/template_module.html
- name: Copy config file
  template:
    src: "osquery.conf.json"
    dest: "{{ osquery_combined.config_include_dir }}/osquery.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart osquery

# http://docs.ansible.com/ansible/latest/template_module.html
- name: Copy config file
  template:
    src: "sysctl.conf.j2"
    dest: "/etc/sysctl.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart osquery

# http://docs.ansible.com/ansible/latest/service_module.html
- name: Make sure osquery autostarts
  service:
    name: "{{ osquery_combined.daemon }}"
    enabled: yes

- name: Restart osquery
  service:
    name: "{{ osquery_combined.daemon }}"
    state: restarted
    sleep: 15