---

# http://docs.ansible.com/ansible/latest/set_fact_module.html
- name: Merge osquery_defaults and osquery variables
  set_fact:
    osquery_combined: "{{ osquery_defaults | combine(osquery, recursive=True) }}"

# Include OS-specific installation tasks.
- include_tasks: setup-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when:
    - ansible_os_family == 'Debian'



# http://docs.ansible.com/ansible/latest/template_module.html
- name: Copy config file
  template:
    src: "osquery.conf.json"
    dest: "{{ osquery_combined.config_include_dir }}/osquery.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart osquery

# http://docs.ansible.com/ansible/latest/template_module.html
- name: Copy config file
  template:
    src: "sysctl.conf.j2"
    dest: "/etc/sysctl.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart osquery

# http://docs.ansible.com/ansible/latest/service_module.html
- name: Make sure osquery autostarts
  service:
    name: "{{ osquery_combined.daemon }}"
    enabled: yes
  when:
    - osquery_combined.enable_service

- name: Restart osquery
  service:
    name: "{{ osquery_combined.daemon }}"
    state: restarted
  when:
    - osquery_combined.enable_service
